spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:kanan.gurbanov.02@gmail.com}
    password: ${MAIL_PASSWORD:qwertykenan123456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true




